spring:
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: password
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  datasource:
    # url: jdbc:postgresql://localhost:5432/aurorademo
    driver-class-name: org.postgresql.Driver
    username: app_pgrw
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: aws-secretsmanager:local/dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    use-unix-domain-sockets: true

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
